# Generated by Django 3.2.19 on 2023-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=24)),
                ('date_occurred', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
            ],
        ),
    ]
