# Generated by Django 3.2.19 on 2023-08-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('checkout', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profile_app.websiteuser'),
        ),
    ]
