# Generated by Django 3.2.19 on 2023-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('roast', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('origin', models.CharField(max_length=254)),
                ('bag_100g_USD', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
