# Generated by Django 3.2.19 on 2023-06-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bag_100g_USD',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
