# Generated by Django 3.2.19 on 2023-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_bag_100g_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roast',
            field=models.IntegerField(),
        ),
    ]
