# Generated by Django 3.2.19 on 2023-06-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_roast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roast',
            field=models.IntegerField(choices=[(1, 'Light'), (2, 'Medium-Light'), (3, 'Medium'), (4, 'Medium-Dark'), (5, 'Dark')]),
        ),
    ]
