# Generated by Django 3.2.19 on 2023-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_roast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Africa', 'Africa'), ('South America', 'South America'), ('Central America', 'Central America'), ('North America', 'North America'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Oceania', 'Oceania')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='roast',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium-Light', 'Medium-Light'), ('Medium', 'Medium'), ('Medium-Dark', 'Medium-Dark'), ('Dark', 'Dark')], max_length=254),
        ),
    ]
